# Generated by Django 5.0.6 on 2026-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='permission_level',
            field=models.CharField(choices=[('private', 'Private'), ('read_only', 'Read-only'), ('public', 'Public')], default='private', help_text='Controls whether other logged-in users can see/edit this node.', max_length=16),
        ),
    ]
